name: build and deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Generate Stats Card
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&show_icons=true&count_private=true&locale=cn"
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Stats Card (Dark)
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: stats
          options: "username=${{ github.repository_owner }}&theme=nord&show_icons=true&count_private=true&locale=cn"
          path: profile/stats.nord.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}&layout=compact&show_icons=true&count_private=true&locale=cn"
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages Card (Dark)
        uses: stats-organization/github-readme-stats-action@v1
        with:
          card: top-langs
          options: "username=${{ github.repository_owner }}&layout=compact&theme=nord&show_icons=true&count_private=true&locale=cn"
          path: profile/top-langs.nord.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Copy Index.html
        run: cp README.md profile/index.html
      
      - name: Build With Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: profile
          destination: _site

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

  deploy:
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  workflow-keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest

    permissions:
      actions: write

    steps:
      - uses: liskin/gh-workflow-keepalive@v1
